DROP TABLE IF EXISTS User;

CREATE TABLE User (
    id serial NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(60) unique NOT NULL,
    password VARCHAR(60) NOT NULL, 
    firstName VARCHAR(60) NOT NULL,
    lastName VARCHAR(60) NOT NULL, 
    email VARCHAR(60) unique NOT NULL,
    role TINYINT NOT NULL,
);

--DROP TABLE IF EXISTS Car;